### ISSUE TITLE
Move pi-hole to it's own networking profile

### ISSUE THREAD

**Issue by jessebot** [jessebot/onboardme#10]
This one is part of automating Pi-Hole, specifically for automating block-list sharing 🤷 

From another machine profile:

```yaml
---
Sqlite:
  - Database: "/etc/pihole/gravity.db"
    Table: "adlist"
    Columns: "address, enabled, comment"
    Type: "insert"
    Values:
      - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
      - "https://adaway.org/hosts.txt"
      - "https://v.firebog.net/hosts/AdguardDNS.txt"
      - "https://v.firebog.net/hosts/Admiral.txt"
      - "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt"
      - "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt"
      - "https://v.firebog.net/hosts/Easylist.txt"
      - "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts"
      - "https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts"
      - "https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts"
      - "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts"
      - "https://v.firebog.net/hosts/static/w3kbl.txt"
      - "https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt"
      - "https://someonewhocares.org/hosts/zero/hosts"
      - "https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts"
      - "https://winhelp2002.mvps.org/hosts.txt"
      - "https://v.firebog.net/hosts/neohostsbasic.txt"
      - "https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt"
      - "https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt"
      - "https://v.firebog.net/hosts/Easyprivacy.txt"
      - "https://v.firebog.net/hosts/Prigent-Ads.txt"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts"
      - "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt"
      - "https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt"
      - "https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/kees1958.txt"
      - "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt"
      - "https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt"
      - "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt"
      - "https://v.firebog.net/hosts/Prigent-Crypto.txt"
      - "https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt"
      - "https://phishing.army/download/phishing_army_blocklist_extended.txt"
      - "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt"
      - "https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts"
      - "https://urlhaus.abuse.ch/downloads/hostfile/"
      - "https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser"
      - "https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list"
      - "https://v.firebog.net/hosts/Prigent-Adult.txt"
      - "https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt"
  - Database: "/etc/pihole/gravity.db"
    Table: "adlist"
    Type: "create_table"
    Schema: 
      - Name: "address"
        Type: "TEXT"
        Constraint: "PRIMARY KEY"
      - Name: "enabled"
        Type: "TEXT"
        Constraint: "NOT NULL"
      - Name: "comment"
        Type: "TEXT"
        Constraint: "NOT NULL"
```

_Originally posted by @cloudymax in https://github.com/jessebot/onboardme/pull/9#discussion_r889281660_
