### ISSUE TITLE
Feature Request: default tmux sessions, starting with a jukebox 🎶

### ISSUE THREAD

**Issue by jessebot** [jessebot/onboardme#129]
## Describe the feature you'd like, and why
In the config file, we should have an option for allowing automatic creation of **named** `tmux`(or other terminal multiplexers like [`zellij`](https://zellij.dev/documentation/overview.html)) sessions and what to run in them.

If the tmux session name doesn't exist already, we should create it by default. We should have this be off by default, and be an opt in feature, because a bunch of tmux sessions everywhere, sounds like pain to clean up, but here's an idea of how the feature would work:

### Config File Update proposal [Draft1]

```yaml
terminal_multiplexer: 
  # change this to true, to enable terminal multiplexer sessions
  enabled: false
  # this can be any program name, but we'll support tmux and zellij out of the box
  program_name: zellij
  # name of the session to create with: tmux new -s name
  # we will only create this if it doesn't already exist
  - session_name: spotify_tui
    command: spt
```

then we could generate a script to automatically create a session for them, or just do it for them by putting that script in a cronjob to make sure those sessions always exist.
