### ISSUE TITLE
Change font for docs currently in github pages?

### ISSUE THREAD

**Issue by jessebot** [jessebot/onboardme#33]
powerline fonts broken in some places in docs.

Goal: have nerdfonts in docs.

Feature-bug. it's a maybe easy thing to do 🤷

**Comment by jessebot** [comment]
I found this stackoverflow page:
https://stackoverflow.com/questions/35718750/adding-custom-fonts-to-github-pages

and so I am trying to do this instead: https://github.com/jessebot/onboardme/commit/4438db64fdb0298d10c1dc76af62ba3d9b98e352 :

```scss
  @font-face {
    font-family: "mononoki";
    src: url("../../onboardme/docs/fonts/mononoki-Regular-Nerd-Font-Complete.ttf") format('truetype');
  }
```

🤷
