### ISSUE TITLE
Move brew back to packages.yml and document how to use packages.yml locally

### ISSUE THREAD

**Issue by jessebot** [jessebot/onboardme#83]
This current system is confusing to new users:

There's a global `.Brewfile` here, but only if you clone my dot files, which the user can override:
https://github.com/jessebot/dot_files/blob/main/.Brewfile

And then there's additional `Brewfile`s here for other install paths for devops and macOS specific stuff:
https://github.com/jessebot/onboardme/tree/v0.15.0/onboardme/config/brew

This also requires a special function to manage these two locations, and it is not as easy to make sure that duplicates between other package managers don't happen.

Finally, this makes documenting using the existing `packages.yml` more difficult, and the file should be easy to grasp and edit on your own.

Brew needs to have similar formatting to the other package managers, so something like:
```yaml
brew:
  emoji: "🍺"
  commands:
    list: "brew list"
    update: "brew update --quiet"
    upgrade: "brew upgrade --quiet"
    install: "brew install "
    cleanup: "brew cleanup"
  packages:
    # these are all for both macOS and Debian
    default:
      # for testing apis and downloading things
      - curl
      - wget
```

And to get around the cask issue, we'll just add "--cask" before commands that need it, e.g. `--cask rectangle`
